# Table of Content
01. Import Libraries
02. Import Data
03. Change Column Data Type (if necessary)
04. Find Mixed-type Data
05. Data Accuracy
06. Data Consistency
07. Data Duplicates
08. Missing Values
09. Export Data

# 01. Import Libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Adjust the setting to view all rows
pd.options.display.max_rows = None

In [3]:
# Adjust the setting to view all columns
pd.options.display.max_columns = None

# 02. Import Data

In [4]:
# Define the main project folder path
path = r'C:\Users\saich\Desktop\CareerFoundry\Data Immersion\Achievement 6 Advanced Analytics & Dashboard Design\11-2023 HDB Flat Resale Analysis'

In [5]:
# Import the 'MRT_LRT (combined)' sheet from 'train_station.xlsx' under 'Original Data' folder
# This file contains the opening and closure dates for all train stations (extracted from Wikipedia)
# https://en.wikipedia.org/wiki/List_of_Singapore_MRT_stations
# https://en.wikipedia.org/wiki/List_of_Singapore_LRT_stations

train_station = pd.read_excel(os.path.join(path, '02 Data', 'Original Data', 'train_station.xlsx'), 
                               sheet_name = 'MRT_LRT (combined)')

In [6]:
train_station

,station_code,station_name,line,opening,closure
0,NS1,Jurong East,North-South Line,10 March 1990,NaN
1,NS2,Bukit Batok,North-South Line,10 March 1990,NaN
2,NS3,Bukit Gombak,North-South Line,10 March 1990,NaN
3,NS4,Choa Chu Kang,North-South Line,10 March 1990,NaN
4,NS5,Yew Tee,North-South Line,10 February 1996,NaN
5,NS7,Kranji,North-South Line,10 February 1996,NaN
6,NS8,Marsiling,North-South Line,10 February 1996,NaN
7,NS9,Woodlands,North-South Line,10 February 1996,NaN
8,NS10,Admiralty,North-South Line,10 February 1996,NaN
9,NS11,Sembawang,North-South Line,10 February 1996,NaN
10,NS12,Canberra,North-South Line,2 November 2019,NaN
11,NS13,Yishun,North-South Line,20 December 1988,NaN
12,NS14,Khatib,North-South Line,20 December 1988,NaN
13,NS15,Yio Chu Kang,North-South Line,7 November 1987,NaN
14,NS16,Ang Mo Kio,North-South Line,7 November 1987,NaN
15,NS17,Bishan,North-South Line,7 November 1987,NaN
16,NS18,Braddell,North-South Line,7 November 1987,NaN
17,NS19,Toa Payoh,North-South Line,7 November 1987,NaN
18,NS20,Novena,North-South Line,12 December 1987,NaN
19,NS21,Newton,North-South Line,12 December 1987,NaN
20,NS22,Orchard,North-South Line,12 December 1987,NaN
21,NS23,Somerset,North-South Line,12 December 1987,NaN
22,NS24,Dhoby Ghaut,North-South Line,12 December 1987,NaN
23,NS25,City Hall,North-South Line,12 December 1987,NaN
24,NS26,Raffles Place,North-South Line,12 December 1987,NaN
25,NS27,Marina Bay,North-South Line,4 November 1989,NaN
26,NS28,Marina South Pier,North-South Line,23 November 2014,NaN
27,EW1,Pasir Ris,East-West Line,16 December 1989,NaN
28,EW2,Tampines,East-West Line,16 December 1989,NaN
29,EW3,Simei,East-West Line,16 December 1989,NaN
30,EW4,Tanah Merah,East-West Line,4 November 1989,NaN
31,EW5,Bedok,East-West Line,4 November 1989,NaN
32,EW6,Kembangan,East-West Line,4 November 1989,NaN
33,EW7,Eunos,East-West Line,4 November 1989,NaN
34,EW8,Paya Lebar,East-West Line,4 November 1989,NaN
35,EW9,Aljunied,East-West Line,4 November 1989,NaN
36,EW10,Kallang,East-West Line,4 November 1989,NaN
37,EW11,Lavender,East-West Line,4 November 1989,NaN
38,EW12,Bugis,East-West Line,4 November 1989,NaN
39,EW13,City Hall,East-West Line,12 December 1987,NaN
40,EW14,Raffles Place,East-West Line,12 December 1987,NaN
41,EW15,Tanjong Pagar,East-West Line,12 December 1987,NaN
42,EW16,Outram Park,East-West Line,12 December 1987,NaN
43,EW17,Tiong Bahru,East-West Line,12 March 1988,NaN
44,EW18,Redhill,East-West Line,12 March 1988,NaN
45,EW19,Queenstown,East-West Line,12 March 1988,NaN
46,EW20,Commonwealth,East-West Line,12 March 1988,NaN
47,EW21,Buona Vista,East-West Line,12 March 1988,NaN
48,EW22,Dover,East-West Line,18 October 2001,NaN
49,EW23,Clementi,East-West Line,12 March 1988,NaN
50,EW24,Jurong East,East-West Line,5 November 1988,NaN
51,EW25,Chinese Garden,East-West Line,5 November 1988,NaN
52,EW26,Lakeside,East-West Line,5 November 1988,NaN
53,EW27,Boon Lay,East-West Line,6 July 1990,NaN
54,EW28,Pioneer,East-West Line,28 February 2009,NaN
55,EW29,Joo Koon,East-West Line,28 February 2009,NaN
56,EW30,Gul Circle,East-West Line,18 June 2017,NaN
57,EW31,Tuas Crescent,East-West Line,18 June 2017,NaN
58,EW32,Tuas West Road,East-West Line,18 June 2017,NaN
59,EW33,Tuas Link,East-West Line,18 June 2017,NaN
60,CG1,Expo,Changi Airport Branch Line,10 January 2001,NaN
61,CG2,Changi Airport,Changi Airport Branch Line,8 February 2002,NaN
62,NE1,HarbourFront,North East Line,20 June 2003,NaN
63,NE3,Outram Park,North East Line,20 June 2003,NaN
64,NE4,Chinatown,North East Line,20 June 2003,NaN
65,NE5,Clarke Quay,North East Line,20 June 2003,NaN
66,NE6,Dhoby Ghaut,North East Line,20 June 2003,NaN
67,NE7,Little India,North East Line,20 June 2003,NaN
68,NE8,Farrer Park,North East Line,20 June 2003,NaN
69,NE9,Boon Keng,North East Line,20 June 2003,NaN
70,NE10,Potong Pasir,North East Line,20 June 2003,NaN
71,NE11,Woodleigh,North East Line,20 June 2011,NaN
72,NE12,Serangoon,North East Line,20 June 2003,NaN
73,NE13,Kovan,North East Line,20 June 2003,NaN
74,NE14,Hougang,North East Line,20 June 2003,NaN
75,NE15,Buangkok,North East Line,15 January 2006,NaN
76,NE16,Sengkang,North East Line,20 June 2003,NaN
77,NE17,Punggol,North East Line,20 June 2003,NaN
78,CC1,Dhoby Ghaut,Circle Line,17 April 2010,NaN
79,CC2,Bras Basah,Circle Line,17 April 2010,NaN
80,CC3,Esplanade,Circle Line,17 April 2010,NaN
81,CC4,Promenade,Circle Line,17 April 2010,NaN
82,CC5,Nicoll Highway,Circle Line,17 April 2010,NaN
83,CC6,Stadium,Circle Line,17 April 2010,NaN
84,CC7,Mountbatten,Circle Line,17 April 2010,NaN
85,CC8,Dakota,Circle Line,17 April 2010,NaN
86,CC9,Paya Lebar,Circle Line,17 April 2010,NaN
87,CC10,MacPherson,Circle Line,17 April 2010,NaN
88,CC11,Tai Seng,Circle Line,17 April 2010,NaN
89,CC12,Bartley,Circle Line,28 May 2009,NaN
90,CC13,Serangoon,Circle Line,28 May 2009,NaN
91,CC14,Lorong Chuan,Circle Line,28 May 2009,NaN
92,CC15,Bishan,Circle Line,28 May 2009,NaN
93,CC16,Marymount,Circle Line,28 May 2009,NaN
94,CC17,Caldecott,Circle Line,8 October 2011,NaN
95,CC19,Botanic Gardens,Circle Line,8 October 2011,NaN
96,CC20,Farrer Road,Circle Line,8 October 2011,NaN
97,CC21,Holland Village,Circle Line,8 October 2011,NaN
98,CC22,Buona Vista,Circle Line,8 October 2011,NaN
99,CC23,one-north,Circle Line,8 October 2011,NaN
100,CC24,Kent Ridge,Circle Line,8 October 2011,NaN
101,CC25,Haw Par Villa,Circle Line,8 October 2011,NaN
102,CC26,Pasir Panjang,Circle Line,8 October 2011,NaN
103,CC27,Labrador Park,Circle Line,8 October 2011,NaN
104,CC28,Telok Blangah,Circle Line,8 October 2011,NaN
105,CC29,HarbourFront,Circle Line,8 October 2011,NaN
106,CE1,Bayfront,Circle Line Extension,14 January 2012,NaN
107,CE2,Marina Bay,Circle Line Extension,14 January 2012,NaN
108,DT1,Bukit Panjang,Downtown Line,27 December 2015,NaN
109,DT2,Cashew,Downtown Line,27 December 2015,NaN
110,DT3,Hillview,Downtown Line,27 December 2015,NaN
111,DT5,Beauty World,Downtown Line,27 December 2015,NaN
112,DT6,King Albert Park,Downtown Line,27 December 2015,NaN
113,DT7,Sixth Avenue,Downtown Line,27 December 2015,NaN
114,DT8,Tan Kah Kee,Downtown Line,27 December 2015,NaN
115,DT9,Botanic Gardens,Downtown Line,27 December 2015,NaN
116,DT10,Stevens,Downtown Line,27 December 2015,NaN
117,DT11,Newton,Downtown Line,27 December 2015,NaN
118,DT12,Little India,Downtown Line,27 December 2015,NaN
119,DT13,Rochor,Downtown Line,27 December 2015,NaN
120,DT14,Bugis,Downtown Line,22 December 2013,NaN
121,DT15,Promenade,Downtown Line,22 December 2013,NaN
122,DT16,Bayfront,Downtown Line,22 December 2013,NaN
123,DT17,Downtown,Downtown Line,22 December 2013,NaN
124,DT18,Telok Ayer,Downtown Line,22 December 2013,NaN
125,DT19,Chinatown,Downtown Line,22 December 2013,NaN
126,DT20,Fort Canning,Downtown Line,21 October 2017,NaN
127,DT21,Bencoolen,Downtown Line,21 October 2017,NaN
128,DT22,Jalan Besar,Downtown Line,21 October 2017,NaN
129,DT23,Bendemeer,Downtown Line,21 October 2017,NaN
130,DT24,Geylang Bahru,Downtown Line,21 October 2017,NaN
131,DT25,Mattar,Downtown Line,21 October 2017,NaN
132,DT26,MacPherson,Downtown Line,21 October 2017,NaN
133,DT27,Ubi,Downtown Line,21 October 2017,NaN
134,DT28,Kaki Bukit,Downtown Line,21 October 2017,NaN
135,DT29,Bedok North,Downtown Line,21 October 2017,NaN
136,DT30,Bedok Reservoir,Downtown Line,21 October 2017,NaN
137,DT31,Tampines West,Downtown Line,21 October 2017,NaN
138,DT32,Tampines,Downtown Line,21 October 2017,NaN
139,DT33,Tampines East,Downtown Line,21 October 2017,NaN
140,DT34,Upper Changi,Downtown Line,21 October 2017,NaN
141,DT35,Expo,Downtown Line,21 October 2017,NaN
142,TE1,Woodlands North,Thomsom-East Coast Line,31 January 2020,NaN
143,TE2,Woodlands,Thomsom-East Coast Line,31 January 2020,NaN
144,TE3,Woodlands South,Thomsom-East Coast Line,31 January 2020,NaN
145,TE4,Springleaf,Thomsom-East Coast Line,28 August 2021,NaN
146,TE5,Lentor,Thomsom-East Coast Line,28 August 2021,NaN
147,TE6,Mayflower,Thomsom-East Coast Line,28 August 2021,NaN
148,TE7,Bright Hill,Thomsom-East Coast Line,28 August 2021,NaN
149,TE8,Upper Thomson,Thomsom-East Coast Line,28 August 2021,NaN
150,TE9,Caldecott,Thomsom-East Coast Line,28 August 2021,NaN
151,TE11,Stevens,Thomsom-East Coast Line,13 November 2022,NaN
152,TE12,Napier,Thomsom-East Coast Line,13 November 2022,NaN
153,TE13,Orchard Boulevard,Thomsom-East Coast Line,13 November 2022,NaN
154,TE14,Orchard,Thomsom-East Coast Line,13 November 2022,NaN
155,TE15,Great World,Thomsom-East Coast Line,13 November 2022,NaN
156,TE16,Havelock,Thomsom-East Coast Line,13 November 2022,NaN
157,TE17,Outram Park,Thomsom-East Coast Line,13 November 2022,NaN
158,TE18,Maxwell,Thomsom-East Coast Line,13 November 2022,NaN
159,TE19,Shenton Way,Thomsom-East Coast Line,13 November 2022,NaN
160,TE20,Marina Bay,Thomsom-East Coast Line,13 November 2022,NaN
161,TE22,Gardens by the Bay,Thomsom-East Coast Line,13 November 2022,NaN
162,BP1,Choa Chu Kang,Bukit Panjang LRT,6 November 1999,NaN
163,BP2,South View,Bukit Panjang LRT,6 November 1999,NaN
164,BP3,Keat Hong,Bukit Panjang LRT,6 November 1999,NaN
165,BP4,Teck Whye,Bukit Panjang LRT,6 November 1999,NaN
166,BP5,Phoenix,Bukit Panjang LRT,6 November 1999,NaN
167,BP6,Bukit Panjang,Bukit Panjang LRT,6 November 1999,NaN
168,BP7,Petir,Bukit Panjang LRT,6 November 1999,NaN
169,BP8,Pending,Bukit Panjang LRT,6 November 1999,NaN
170,BP9,Bangkit,Bukit Panjang LRT,6 November 1999,NaN
171,BP10,Fajar,Bukit Panjang LRT,6 November 1999,NaN
172,BP11,Segar,Bukit Panjang LRT,6 November 1999,NaN
173,BP12,Jelapang,Bukit Panjang LRT,6 November 1999,NaN
174,BP13,Senja,Bukit Panjang LRT,6 November 1999,NaN
175,BP14,Ten Mile Junction,Bukit Panjang LRT,6 November 1999,13 January 2019
176,STC,Sengkang,Sengkang LRT,18 January 2003,NaN
177,SE1,Compassvale,Sengkang LRT,18 January 2003,NaN
178,SE2,Rumbia,Sengkang LRT,18 January 2003,NaN
179,SE3,Bakau,Sengkang LRT,18 January 2003,NaN
180,SE4,Kangkar,Sengkang LRT,18 January 2003,NaN
181,SE5,Ranggung,Sengkang LRT,18 January 2003,NaN
182,SW1,Cheng Lim,Sengkang LRT,1 January 2013,NaN
183,SW2,Farmway,Sengkang LRT,15 November 2007,NaN
184,SW3,Kupang,Sengkang LRT,27 June 2015,NaN
185,SW4,Thanggam,Sengkang LRT,29 January 2005,NaN
186,SW5,Fernvale,Sengkang LRT,29 January 2005,NaN
187,SW6,Layar,Sengkang LRT,29 January 2005,NaN
188,SW7,Tongkang,Sengkang LRT,29 January 2005,NaN
189,SW8,Renjong,Sengkang LRT,29 January 2005,NaN
190,PTC,Punggol,Punggol LRT,29 January 2005,NaN
191,PE1,Cove,Punggol LRT,29 January 2005,NaN
192,PE2,Meridian,Punggol LRT,29 January 2005,NaN
193,PE3,Coral Edge,Punggol LRT,29 January 2005,NaN
194,PE4,Riviera,Punggol LRT,29 January 2005,NaN
195,PE5,Kadaloor,Punggol LRT,29 January 2005,NaN
196,PE6,Oasis,Punggol LRT,15 June 2007,NaN
197,PE7,Damai,Punggol LRT,20 June 2011,NaN
198,PW1,Sam Kee,Punggol LRT,29 February 2016,NaN
199,PW3,Punggol Point,Punggol LRT,29 December 2016,NaN
200,PW4,Samudera,Punggol LRT,31 March 2017,NaN
201,PW5,Nibong,Punggol LRT,29 June 2014,NaN
202,PW6,Sumang,Punggol LRT,29 June 2014,NaN
203,PW7,Soo Teck,Punggol LRT,29 June 2014,NaN

In [7]:
train_station.shape

(204, 5)

# 03. Change Column Data Type (if necessary)

In [8]:
# Check the data type of each column
train_station.dtypes

station_code    object
station_name    object
line            object
opening         object
closure         object
dtype: object

'Opening' and 'Closure' columns store date information. They should be changed into datetime data type.

In [9]:
# Change the data types of 'opening' and 'closure' columns into datetime
train_station['opening'] = pd.to_datetime(train_station['opening'])

In [10]:
train_station['closure'] = pd.to_datetime(train_station['closure'])

In [11]:
train_station

,station_code,station_name,line,opening,closure
0,NS1,Jurong East,North-South Line,1990-03-10,NaT
1,NS2,Bukit Batok,North-South Line,1990-03-10,NaT
2,NS3,Bukit Gombak,North-South Line,1990-03-10,NaT
3,NS4,Choa Chu Kang,North-South Line,1990-03-10,NaT
4,NS5,Yew Tee,North-South Line,1996-02-10,NaT
5,NS7,Kranji,North-South Line,1996-02-10,NaT
6,NS8,Marsiling,North-South Line,1996-02-10,NaT
7,NS9,Woodlands,North-South Line,1996-02-10,NaT
8,NS10,Admiralty,North-South Line,1996-02-10,NaT
9,NS11,Sembawang,North-South Line,1996-02-10,NaT
10,NS12,Canberra,North-South Line,2019-11-02,NaT
11,NS13,Yishun,North-South Line,1988-12-20,NaT
12,NS14,Khatib,North-South Line,1988-12-20,NaT
13,NS15,Yio Chu Kang,North-South Line,1987-11-07,NaT
14,NS16,Ang Mo Kio,North-South Line,1987-11-07,NaT
15,NS17,Bishan,North-South Line,1987-11-07,NaT
16,NS18,Braddell,North-South Line,1987-11-07,NaT
17,NS19,Toa Payoh,North-South Line,1987-11-07,NaT
18,NS20,Novena,North-South Line,1987-12-12,NaT
19,NS21,Newton,North-South Line,1987-12-12,NaT
20,NS22,Orchard,North-South Line,1987-12-12,NaT
21,NS23,Somerset,North-South Line,1987-12-12,NaT
22,NS24,Dhoby Ghaut,North-South Line,1987-12-12,NaT
23,NS25,City Hall,North-South Line,1987-12-12,NaT
24,NS26,Raffles Place,North-South Line,1987-12-12,NaT
25,NS27,Marina Bay,North-South Line,1989-11-04,NaT
26,NS28,Marina South Pier,North-South Line,2014-11-23,NaT
27,EW1,Pasir Ris,East-West Line,1989-12-16,NaT
28,EW2,Tampines,East-West Line,1989-12-16,NaT
29,EW3,Simei,East-West Line,1989-12-16,NaT
30,EW4,Tanah Merah,East-West Line,1989-11-04,NaT
31,EW5,Bedok,East-West Line,1989-11-04,NaT
32,EW6,Kembangan,East-West Line,1989-11-04,NaT
33,EW7,Eunos,East-West Line,1989-11-04,NaT
34,EW8,Paya Lebar,East-West Line,1989-11-04,NaT
35,EW9,Aljunied,East-West Line,1989-11-04,NaT
36,EW10,Kallang,East-West Line,1989-11-04,NaT
37,EW11,Lavender,East-West Line,1989-11-04,NaT
38,EW12,Bugis,East-West Line,1989-11-04,NaT
39,EW13,City Hall,East-West Line,1987-12-12,NaT
40,EW14,Raffles Place,East-West Line,1987-12-12,NaT
41,EW15,Tanjong Pagar,East-West Line,1987-12-12,NaT
42,EW16,Outram Park,East-West Line,1987-12-12,NaT
43,EW17,Tiong Bahru,East-West Line,1988-03-12,NaT
44,EW18,Redhill,East-West Line,1988-03-12,NaT
45,EW19,Queenstown,East-West Line,1988-03-12,NaT
46,EW20,Commonwealth,East-West Line,1988-03-12,NaT
47,EW21,Buona Vista,East-West Line,1988-03-12,NaT
48,EW22,Dover,East-West Line,2001-10-18,NaT
49,EW23,Clementi,East-West Line,1988-03-12,NaT
50,EW24,Jurong East,East-West Line,1988-11-05,NaT
51,EW25,Chinese Garden,East-West Line,1988-11-05,NaT
52,EW26,Lakeside,East-West Line,1988-11-05,NaT
53,EW27,Boon Lay,East-West Line,1990-07-06,NaT
54,EW28,Pioneer,East-West Line,2009-02-28,NaT
55,EW29,Joo Koon,East-West Line,2009-02-28,NaT
56,EW30,Gul Circle,East-West Line,2017-06-18,NaT
57,EW31,Tuas Crescent,East-West Line,2017-06-18,NaT
58,EW32,Tuas West Road,East-West Line,2017-06-18,NaT
59,EW33,Tuas Link,East-West Line,2017-06-18,NaT
60,CG1,Expo,Changi Airport Branch Line,2001-01-10,NaT
61,CG2,Changi Airport,Changi Airport Branch Line,2002-02-08,NaT
62,NE1,HarbourFront,North East Line,2003-06-20,NaT
63,NE3,Outram Park,North East Line,2003-06-20,NaT
64,NE4,Chinatown,North East Line,2003-06-20,NaT
65,NE5,Clarke Quay,North East Line,2003-06-20,NaT
66,NE6,Dhoby Ghaut,North East Line,2003-06-20,NaT
67,NE7,Little India,North East Line,2003-06-20,NaT
68,NE8,Farrer Park,North East Line,2003-06-20,NaT
69,NE9,Boon Keng,North East Line,2003-06-20,NaT
70,NE10,Potong Pasir,North East Line,2003-06-20,NaT
71,NE11,Woodleigh,North East Line,2011-06-20,NaT
72,NE12,Serangoon,North East Line,2003-06-20,NaT
73,NE13,Kovan,North East Line,2003-06-20,NaT
74,NE14,Hougang,North East Line,2003-06-20,NaT
75,NE15,Buangkok,North East Line,2006-01-15,NaT
76,NE16,Sengkang,North East Line,2003-06-20,NaT
77,NE17,Punggol,North East Line,2003-06-20,NaT
78,CC1,Dhoby Ghaut,Circle Line,2010-04-17,NaT
79,CC2,Bras Basah,Circle Line,2010-04-17,NaT
80,CC3,Esplanade,Circle Line,2010-04-17,NaT
81,CC4,Promenade,Circle Line,2010-04-17,NaT
82,CC5,Nicoll Highway,Circle Line,2010-04-17,NaT
83,CC6,Stadium,Circle Line,2010-04-17,NaT
84,CC7,Mountbatten,Circle Line,2010-04-17,NaT
85,CC8,Dakota,Circle Line,2010-04-17,NaT
86,CC9,Paya Lebar,Circle Line,2010-04-17,NaT
87,CC10,MacPherson,Circle Line,2010-04-17,NaT
88,CC11,Tai Seng,Circle Line,2010-04-17,NaT
89,CC12,Bartley,Circle Line,2009-05-28,NaT
90,CC13,Serangoon,Circle Line,2009-05-28,NaT
91,CC14,Lorong Chuan,Circle Line,2009-05-28,NaT
92,CC15,Bishan,Circle Line,2009-05-28,NaT
93,CC16,Marymount,Circle Line,2009-05-28,NaT
94,CC17,Caldecott,Circle Line,2011-10-08,NaT
95,CC19,Botanic Gardens,Circle Line,2011-10-08,NaT
96,CC20,Farrer Road,Circle Line,2011-10-08,NaT
97,CC21,Holland Village,Circle Line,2011-10-08,NaT
98,CC22,Buona Vista,Circle Line,2011-10-08,NaT
99,CC23,one-north,Circle Line,2011-10-08,NaT
100,CC24,Kent Ridge,Circle Line,2011-10-08,NaT
101,CC25,Haw Par Villa,Circle Line,2011-10-08,NaT
102,CC26,Pasir Panjang,Circle Line,2011-10-08,NaT
103,CC27,Labrador Park,Circle Line,2011-10-08,NaT
104,CC28,Telok Blangah,Circle Line,2011-10-08,NaT
105,CC29,HarbourFront,Circle Line,2011-10-08,NaT
106,CE1,Bayfront,Circle Line Extension,2012-01-14,NaT
107,CE2,Marina Bay,Circle Line Extension,2012-01-14,NaT
108,DT1,Bukit Panjang,Downtown Line,2015-12-27,NaT
109,DT2,Cashew,Downtown Line,2015-12-27,NaT
110,DT3,Hillview,Downtown Line,2015-12-27,NaT
111,DT5,Beauty World,Downtown Line,2015-12-27,NaT
112,DT6,King Albert Park,Downtown Line,2015-12-27,NaT
113,DT7,Sixth Avenue,Downtown Line,2015-12-27,NaT
114,DT8,Tan Kah Kee,Downtown Line,2015-12-27,NaT
115,DT9,Botanic Gardens,Downtown Line,2015-12-27,NaT
116,DT10,Stevens,Downtown Line,2015-12-27,NaT
117,DT11,Newton,Downtown Line,2015-12-27,NaT
118,DT12,Little India,Downtown Line,2015-12-27,NaT
119,DT13,Rochor,Downtown Line,2015-12-27,NaT
120,DT14,Bugis,Downtown Line,2013-12-22,NaT
121,DT15,Promenade,Downtown Line,2013-12-22,NaT
122,DT16,Bayfront,Downtown Line,2013-12-22,NaT
123,DT17,Downtown,Downtown Line,2013-12-22,NaT
124,DT18,Telok Ayer,Downtown Line,2013-12-22,NaT
125,DT19,Chinatown,Downtown Line,2013-12-22,NaT
126,DT20,Fort Canning,Downtown Line,2017-10-21,NaT
127,DT21,Bencoolen,Downtown Line,2017-10-21,NaT
128,DT22,Jalan Besar,Downtown Line,2017-10-21,NaT
129,DT23,Bendemeer,Downtown Line,2017-10-21,NaT
130,DT24,Geylang Bahru,Downtown Line,2017-10-21,NaT
131,DT25,Mattar,Downtown Line,2017-10-21,NaT
132,DT26,MacPherson,Downtown Line,2017-10-21,NaT
133,DT27,Ubi,Downtown Line,2017-10-21,NaT
134,DT28,Kaki Bukit,Downtown Line,2017-10-21,NaT
135,DT29,Bedok North,Downtown Line,2017-10-21,NaT
136,DT30,Bedok Reservoir,Downtown Line,2017-10-21,NaT
137,DT31,Tampines West,Downtown Line,2017-10-21,NaT
138,DT32,Tampines,Downtown Line,2017-10-21,NaT
139,DT33,Tampines East,Downtown Line,2017-10-21,NaT
140,DT34,Upper Changi,Downtown Line,2017-10-21,NaT
141,DT35,Expo,Downtown Line,2017-10-21,NaT
142,TE1,Woodlands North,Thomsom-East Coast Line,2020-01-31,NaT
143,TE2,Woodlands,Thomsom-East Coast Line,2020-01-31,NaT
144,TE3,Woodlands South,Thomsom-East Coast Line,2020-01-31,NaT
145,TE4,Springleaf,Thomsom-East Coast Line,2021-08-28,NaT
146,TE5,Lentor,Thomsom-East Coast Line,2021-08-28,NaT
147,TE6,Mayflower,Thomsom-East Coast Line,2021-08-28,NaT
148,TE7,Bright Hill,Thomsom-East Coast Line,2021-08-28,NaT
149,TE8,Upper Thomson,Thomsom-East Coast Line,2021-08-28,NaT
150,TE9,Caldecott,Thomsom-East Coast Line,2021-08-28,NaT
151,TE11,Stevens,Thomsom-East Coast Line,2022-11-13,NaT
152,TE12,Napier,Thomsom-East Coast Line,2022-11-13,NaT
153,TE13,Orchard Boulevard,Thomsom-East Coast Line,2022-11-13,NaT
154,TE14,Orchard,Thomsom-East Coast Line,2022-11-13,NaT
155,TE15,Great World,Thomsom-East Coast Line,2022-11-13,NaT
156,TE16,Havelock,Thomsom-East Coast Line,2022-11-13,NaT
157,TE17,Outram Park,Thomsom-East Coast Line,2022-11-13,NaT
158,TE18,Maxwell,Thomsom-East Coast Line,2022-11-13,NaT
159,TE19,Shenton Way,Thomsom-East Coast Line,2022-11-13,NaT
160,TE20,Marina Bay,Thomsom-East Coast Line,2022-11-13,NaT
161,TE22,Gardens by the Bay,Thomsom-East Coast Line,2022-11-13,NaT
162,BP1,Choa Chu Kang,Bukit Panjang LRT,1999-11-06,NaT
163,BP2,South View,Bukit Panjang LRT,1999-11-06,NaT
164,BP3,Keat Hong,Bukit Panjang LRT,1999-11-06,NaT
165,BP4,Teck Whye,Bukit Panjang LRT,1999-11-06,NaT
166,BP5,Phoenix,Bukit Panjang LRT,1999-11-06,NaT
167,BP6,Bukit Panjang,Bukit Panjang LRT,1999-11-06,NaT
168,BP7,Petir,Bukit Panjang LRT,1999-11-06,NaT
169,BP8,Pending,Bukit Panjang LRT,1999-11-06,NaT
170,BP9,Bangkit,Bukit Panjang LRT,1999-11-06,NaT
171,BP10,Fajar,Bukit Panjang LRT,1999-11-06,NaT
172,BP11,Segar,Bukit Panjang LRT,1999-11-06,NaT
173,BP12,Jelapang,Bukit Panjang LRT,1999-11-06,NaT
174,BP13,Senja,Bukit Panjang LRT,1999-11-06,NaT
175,BP14,Ten Mile Junction,Bukit Panjang LRT,1999-11-06,2019-01-13
176,STC,Sengkang,Sengkang LRT,2003-01-18,NaT
177,SE1,Compassvale,Sengkang LRT,2003-01-18,NaT
178,SE2,Rumbia,Sengkang LRT,2003-01-18,NaT
179,SE3,Bakau,Sengkang LRT,2003-01-18,NaT
180,SE4,Kangkar,Sengkang LRT,2003-01-18,NaT
181,SE5,Ranggung,Sengkang LRT,2003-01-18,NaT
182,SW1,Cheng Lim,Sengkang LRT,2013-01-01,NaT
183,SW2,Farmway,Sengkang LRT,2007-11-15,NaT
184,SW3,Kupang,Sengkang LRT,2015-06-27,NaT
185,SW4,Thanggam,Sengkang LRT,2005-01-29,NaT
186,SW5,Fernvale,Sengkang LRT,2005-01-29,NaT
187,SW6,Layar,Sengkang LRT,2005-01-29,NaT
188,SW7,Tongkang,Sengkang LRT,2005-01-29,NaT
189,SW8,Renjong,Sengkang LRT,2005-01-29,NaT
190,PTC,Punggol,Punggol LRT,2005-01-29,NaT
191,PE1,Cove,Punggol LRT,2005-01-29,NaT
192,PE2,Meridian,Punggol LRT,2005-01-29,NaT
193,PE3,Coral Edge,Punggol LRT,2005-01-29,NaT
194,PE4,Riviera,Punggol LRT,2005-01-29,NaT
195,PE5,Kadaloor,Punggol LRT,2005-01-29,NaT
196,PE6,Oasis,Punggol LRT,2007-06-15,NaT
197,PE7,Damai,Punggol LRT,2011-06-20,NaT
198,PW1,Sam Kee,Punggol LRT,2016-02-29,NaT
199,PW3,Punggol Point,Punggol LRT,2016-12-29,NaT
200,PW4,Samudera,Punggol LRT,2017-03-31,NaT
201,PW5,Nibong,Punggol LRT,2014-06-29,NaT
202,PW6,Sumang,Punggol LRT,2014-06-29,NaT
203,PW7,Soo Teck,Punggol LRT,2014-06-29,NaT

In [12]:
# Verify the changes
train_station.dtypes

station_code            object
station_name            object
line                    object
opening         datetime64[ns]
closure         datetime64[ns]
dtype: object

# 04. Find Mixed-type Data

In [13]:
# Check for any mixed-type columns - no output means no mixed-type data
for col in train_station.columns.tolist():
    weird = (train_station[[col]].applymap(type) != train_station[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (train_station[weird]) > 0:
        print (col)

closure

In [14]:
# Check the unique data types that the 'closure' column contains
# The apply() method in Pandas is used to apply a function along the axis of a DataFrame or Series. 
# In this case, the type function is applied to each element in the selected column. 

train_station['closure'].apply(type).unique()

array([<class 'pandas._libs.tslibs.nattype.NaTType'>,
       <class 'pandas._libs.tslibs.timestamps.Timestamp'>], dtype=object)

The 'closure' column contains a mix of datetime objects and 'NaT' values. This mix of data types triggers the detection of mixed-type data. Should not be an issue.

In [15]:
train_station.applymap(type)

,station_code,station_name,line,opening,closure
0,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
1,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
2,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
4,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
5,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
6,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
7,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
8,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
9,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
10,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
11,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
12,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
13,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
14,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
15,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
16,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
17,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
18,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
19,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
20,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
21,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
22,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
23,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
24,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
25,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
26,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
27,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
28,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
29,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
30,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
31,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
32,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
33,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
34,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
35,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
36,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
37,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
38,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
39,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
40,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
41,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
42,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
43,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
44,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
45,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
46,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
47,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
48,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
49,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
50,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
51,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
52,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
53,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
54,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
55,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
56,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
57,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
58,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
59,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
60,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
61,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
62,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
63,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
64,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
65,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
66,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
67,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
68,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
69,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
70,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
71,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
72,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
73,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
74,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
75,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
76,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
77,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
78,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
79,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
80,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
81,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
82,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
83,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
84,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
85,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
86,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
87,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
88,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
89,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
90,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
91,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
92,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
93,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
94,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
95,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
96,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
97,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
98,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
99,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
100,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
101,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
102,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
103,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
104,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
105,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
106,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
107,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
108,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
109,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
110,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
111,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
112,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
113,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
114,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
115,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
116,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
117,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
118,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
119,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
120,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
121,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
122,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
123,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
124,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
125,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
126,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
127,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
128,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
129,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
130,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
131,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
132,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
133,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
134,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
135,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
136,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
137,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
138,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
139,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>
140,<class 'str'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.nattype.NaTType'>

# 05. Data Accuracy

In [16]:
# Check the descriptive statistics for numerical data
train_station.describe()

                             opening              closure
count                            204                    1
mean   2005-12-23 01:38:49.411764736  2019-01-13 00:00:00
min              1987-11-07 00:00:00  2019-01-13 00:00:00
25%              1998-11-29 18:00:00  2019-01-13 00:00:00
50%              2008-07-07 12:00:00  2019-01-13 00:00:00
75%              2015-12-27 00:00:00  2019-01-13 00:00:00
max              2022-11-13 00:00:00  2019-01-13 00:00:00

No unusual findings.

# 06. Data Consistency

Check the data consistency for each categorical variable

### 06.1 station_code

In [17]:
# Check the unique values of 'Station code' column
train_station['station_code'].value_counts(dropna = False)

station_code
NS1     1
DT34    1
DT24    1
DT25    1
DT26    1
DT27    1
DT28    1
DT29    1
DT30    1
DT31    1
DT32    1
DT33    1
DT35    1
DT22    1
TE1     1
TE2     1
TE3     1
TE4     1
TE5     1
TE6     1
TE7     1
TE8     1
TE9     1
TE11    1
DT23    1
DT21    1
NS2     1
DT8     1
CC28    1
CC29    1
CE1     1
CE2     1
DT1     1
DT2     1
DT3     1
DT5     1
DT6     1
DT7     1
DT9     1
DT20    1
DT10    1
DT11    1
DT12    1
DT13    1
DT14    1
DT15    1
DT16    1
DT17    1
DT18    1
DT19    1
TE12    1
TE13    1
TE14    1
PE1     1
SE5     1
SW1     1
SW2     1
SW3     1
SW4     1
SW5     1
SW6     1
SW7     1
SW8     1
PTC     1
PE2     1
TE15    1
PE3     1
PE4     1
PE5     1
PE6     1
PE7     1
PW1     1
PW3     1
PW4     1
PW5     1
PW6     1
SE4     1
SE3     1
SE2     1
SE1     1
TE16    1
TE17    1
TE18    1
TE19    1
TE20    1
TE22    1
BP1     1
BP2     1
BP3     1
BP4     1
BP5     1
BP6     1
BP7     1
BP8     1
BP9     1
BP10    1
BP11    1
BP12    1
BP13    1
BP14    1
STC     1
CC27    1
CC26    1
CC25    1
EW11    1
EW1     1
EW2     1
EW3     1
EW4     1
EW5     1
EW6     1
EW7     1
EW8     1
EW9     1
EW10    1
EW12    1
EW24    1
EW13    1
EW14    1
EW15    1
EW16    1
EW17    1
EW18    1
EW19    1
EW20    1
EW21    1
EW22    1
NS28    1
NS27    1
NS26    1
NS25    1
NS3     1
NS4     1
NS5     1
NS7     1
NS8     1
NS9     1
NS10    1
NS11    1
NS12    1
NS13    1
NS14    1
NS15    1
NS16    1
NS17    1
NS18    1
NS19    1
NS20    1
NS21    1
NS22    1
NS23    1
NS24    1
EW23    1
EW25    1
CC24    1
CC11    1
CC1     1
CC2     1
CC3     1
CC4     1
CC5     1
CC6     1
CC7     1
CC8     1
CC9     1
CC10    1
CC12    1
EW26    1
CC13    1
CC14    1
CC15    1
CC16    1
CC17    1
CC19    1
CC20    1
CC21    1
CC22    1
CC23    1
NE17    1
NE16    1
NE15    1
NE14    1
EW27    1
EW28    1
EW29    1
EW30    1
EW31    1
EW32    1
EW33    1
CG1     1
CG2     1
NE1     1
NE3     1
NE4     1
NE5     1
NE6     1
NE7     1
NE8     1
NE9     1
NE10    1
NE11    1
NE12    1
NE13    1
PW7     1
Name: count, dtype: int64

No unusual findings.

### 06.2 station_name

In [18]:
# Check the unique values of 'station_name' column
train_station['station_name'].value_counts(dropna = False)

station_name
Dhoby Ghaut           3
Marina Bay            3
Outram Park           3
Chinatown             2
Raffles Place         2
Tampines              2
Paya Lebar            2
Bugis                 2
Buona Vista           2
Expo                  2
HarbourFront          2
Jurong East           2
City Hall             2
Serangoon             2
Sengkang              2
Punggol               2
Promenade             2
MacPherson            2
Caldecott             2
Bayfront              2
Bukit Panjang         2
Stevens               2
Little India          2
Botanic Gardens       2
Orchard               2
Newton                2
Choa Chu Kang         2
Woodlands             2
Bishan                2
Somerset              1
Bright Hill           1
Woodlands North       1
Woodlands South       1
Springleaf            1
Lentor                1
Mayflower             1
Orchard Boulevard     1
Upper Thomson         1
Napier                1
Great World           1
Havelock              1
Maxwell               1
Shenton Way           1
Gardens by the Bay    1
Upper Changi          1
Tampines West         1
Tampines East         1
Jalan Besar           1
Bukit Gombak          1
Rochor                1
Downtown              1
Telok Ayer            1
Fort Canning          1
Bencoolen             1
Bendemeer             1
Keat Hong             1
Geylang Bahru         1
Mattar                1
Ubi                   1
Kaki Bukit            1
Bedok North           1
Bedok Reservoir       1
South View            1
Teck Whye             1
Sixth Avenue          1
Phoenix               1
Layar                 1
Tongkang              1
Renjong               1
Cove                  1
Meridian              1
Coral Edge            1
Riviera               1
Kadaloor              1
Oasis                 1
Damai                 1
Sam Kee               1
Punggol Point         1
Samudera              1
Nibong                1
Sumang                1
Fernvale              1
Thanggam              1
Kupang                1
Senja                 1
Petir                 1
Pending               1
Bangkit               1
Fajar                 1
Segar                 1
Jelapang              1
Ten Mile Junction     1
Farmway               1
Compassvale           1
Rumbia                1
Bakau                 1
Kangkar               1
Ranggung              1
Cheng Lim             1
Tan Kah Kee           1
Hillview              1
King Albert Park      1
Joo Koon              1
Dover                 1
Clementi              1
Chinese Garden        1
Lakeside              1
Boon Lay              1
Pioneer               1
Gul Circle            1
Queenstown            1
Tuas Crescent         1
Tuas West Road        1
Tuas Link             1
Ang Mo Kio            1
Changi Airport        1
Yio Chu Kang          1
Commonwealth          1
Redhill               1
Clarke Quay           1
Eunos                 1
Marina South Pier     1
Pasir Ris             1
Simei                 1
Tanah Merah           1
Bedok                 1
Kembangan             1
Novena                1
Tiong Bahru           1
Aljunied              1
Kallang               1
Lavender              1
Toa Payoh             1
Tanjong Pagar         1
Braddell              1
Khatib                1
Yishun                1
Beauty World          1
one-north             1
Lorong Chuan          1
Marymount             1
Kranji                1
Bukit Batok           1
Farrer Road           1
Holland Village       1
Kent Ridge            1
Tai Seng              1
Haw Par Villa         1
Pasir Panjang         1
Labrador Park         1
Telok Blangah         1
Yew Tee               1
Cashew                1
Bartley               1
Marsiling             1
Farrer Park           1
Buangkok              1
Boon Keng             1
Potong Pasir          1
Woodleigh             1
Canberra              1
Kovan                 1
Hougang               1
Sembawang             1
Dakota                1
Admiralty             1
Bras Basah            1
Esplanade             1
Nicoll Highway        1
Stadium               1
Mountbatten           1
Soo Teck              1
Name: count, dtype: int64

No unusual findings.

### 06.3 line

In [19]:
# Check the unique values of 'line' column
train_station['line'].value_counts(dropna = False)

line
Downtown Line                 34
East-West Line                33
Circle Line                   28
North-South Line              27
Thomsom-East Coast Line       20
North East Line               16
Bukit Panjang LRT             14
Sengkang LRT                  14
Punggol LRT                   14
Changi Airport Branch Line     2
Circle Line Extension          2
Name: count, dtype: int64

No unusual findings.

# 07. Data Duplicates

In [20]:
# Check if there are any full duplicates in the dataframe
train_station.duplicated().sum()

0

In [21]:
train_station.loc[train_station.duplicated()]

Empty DataFrame
Columns: [station_code, station_name, line, opening, closure]
Index: []

No unusual findings.

# 08. Missing Values

In [22]:
# Check the number of missing values in each column
train_station.isnull().sum()

station_code      0
station_name      0
line              0
opening           0
closure         203
dtype: int64

There are 203 missing values in 'closure' column. 
This is because the train stations are still in operation, therefore they have no closure dates.

# 09. Export Data

In [23]:
train_station.shape

(204, 5)

In [24]:
# Export data to 'Prepared Data' folder in csv format
train_station.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'train_station (checked).csv'))